# Generated by Django 2.2.2 on 2019-07-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitan',
            name='carne',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='capitan',
            name='nombreEquipo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='capitan',
            name='numeroDocumento',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='carne',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
