# Generated by Django 2.2.2 on 2019-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_auto_20190704_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitan',
            name='semestre',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='capitan',
            name='semestreGrado',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='carne',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
