# Generated by Django 2.2.2 on 2019-07-07 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0006_auto_20190704_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrante',
            name='semestre',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2019-I', editable=False, max_length=6)),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaFin', models.DateField()),
                ('primerPuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primerPuesto', to='torneo.Capitan')),
                ('segundoPuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundoPuesto', to='torneo.Capitan')),
                ('tercerPuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tercerPuesto', to='torneo.Capitan')),
            ],
        ),
    ]
